name: niira
description: kaja

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter_spinkit:
  enum_to_string:
  geolocator:
  google_maps_flutter:
  permission_handler:
  geoflutterfire: 

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  pedantic:

flutter:
  uses-material-design: true
