name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - release

jobs:
  build:
    name: Tests
    runs-on: macOS-latest
    
    steps:

    # output the build number used in this job
    - name: Output Run Info
      run: echo "build-number=$GITHUB_RUN_NUMBER, event = ${{ github.event_name }}, branch = ${{ github.ref }}, target = ${{ github.base_ref }}"

    # several actions use checkout
    - name: Install checkout
      uses: actions/checkout@v2
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action seems to need java
    - name: Install Java for Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    
    ##############################################
    # run tests, build android, build ios
    ##############################################
    - run: flutter pub get
    - run: flutter test --coverage

    ##############################################
    # upload coverage to coveralls.io
    ##############################################
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}